# Generated by Django 4.2.6 on 2024-02-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
